In [1]:
import tensorflow as tf

initialize tensor

In [6]:
x = tf.constant(4, shape=(1,1))
x

In [ ]:
x = tf.constant([[1,2,3], [4,5,6]])
x

In [10]:
x = tf.ones((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [11]:
x = tf.zeros((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [12]:
x = tf.eye(3)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [13]:
x = tf.random.normal((3,3), mean=0, stddev=1)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.75028026,  0.9065277 , -0.2533085 ],
       [-1.3684728 , -0.9078145 , -0.3999919 ],
       [-0.701288  ,  0.27508515, -0.07135644]], dtype=float32)>

In [14]:
x = tf.random.uniform((1,3), minval=0, maxval=1)
x

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.1396401 , 0.41003597, 0.4931668 ]], dtype=float32)>

In [16]:
x = tf.range(start=1, limit=10, delta=2)
x

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

In [17]:
x = tf.cast(x, dtype=tf.float64)
x


<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 3., 5., 7., 9.])>

mathematics operations

In [19]:
x = tf.constant([5,4,3])
y = tf.constant([5,6,7])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [20]:
z = tf.add(x,y)
z = x + y
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [21]:
z = tf.subtract(x,y)
z = x - y
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 0, -2, -4], dtype=int32)>

In [23]:
z = tf.divide(x,y)
z = x / y
z

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1.        , 0.66666667, 0.42857143])>

In [24]:
z = tf.multiply(x,y)
z = x * y
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([25, 24, 21], dtype=int32)>

In [28]:
z = tf.tensordot(x,y, axes=1)
z = tf.reduce_sum(x*y, axis=0)
z

<tf.Tensor: shape=(), dtype=int32, numpy=70>

In [29]:
z = x ** 5
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3125, 1024,  243], dtype=int32)>

In [31]:
x = tf.random.normal((2,3))
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.28225866,  0.1486136 , -1.0302655 ],
       [-1.4859383 , -0.3000359 ,  1.8952366 ]], dtype=float32)>

In [32]:
y = tf.random.normal((3,4))
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.9790234 , -0.47831523,  0.7267521 ,  0.78596234],
       [-0.7707784 , -2.1109335 , -0.9401842 , -1.7941811 ],
       [-0.11457477, -0.05340786,  0.77923536,  1.0284395 ]],
      dtype=float32)>

In [33]:
z = tf.matmul(x,y)
z

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-0.27284354, -0.12368055, -1.1476755 , -1.54805   ],
       [-1.4406534 ,  1.2428824 ,  0.6790155 ,  1.3195635 ]],
      dtype=float32)>

In [34]:
z = x @ y
z

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-0.27284354, -0.12368055, -1.1476755 , -1.54805   ],
       [-1.4406534 ,  1.2428824 ,  0.6790155 ,  1.3195635 ]],
      dtype=float32)>

Indexing tensor

In [35]:
 x = tf.constant([1,3,2,1,0,5,3,0,7,4])
 x[:]

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 3, 2, 1, 0, 5, 3, 0, 7, 4], dtype=int32)>

In [37]:
x[1:] # get all elem except first

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([3, 2, 1, 0, 5, 3, 0, 7, 4], dtype=int32)>

In [38]:
x[1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [39]:
x[::2] # for skipping two

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 0, 3, 7], dtype=int32)>

In [40]:
x[::-1] # reverse

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([4, 7, 0, 3, 5, 0, 1, 2, 3, 1], dtype=int32)>

In [49]:
indices = tf.constant([0,5])
x_ing = tf.gather(x, indices)
x_ing


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 5], dtype=int32)>

In [52]:
x = tf.constant([[3,2],
                 [6,5],
                 [9,3]])
x[0,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [53]:
x[0:2,:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 2],
       [6, 5]], dtype=int32)>

Reshaping

In [55]:
x = tf.range(9)
x = tf.reshape(x, (3,3))
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [56]:
x = tf.transpose(x, perm=(1,0))
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]], dtype=int32)>